name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
#This workflow contains single job called build  
  build:
    # name: Build
    runs-on: ubuntu-latest
    steps:
        - name: Run one line command 
          run: echo "The job was automatically triggered by"
